import { defineField, defineType } from "sanity";

const linkField = defineField({
  name: "link",
  title: "Link",
  type: "object",
  fields: [
    defineField({ name: "label", title: "Label", type: "string" }),
    defineField({ name: "href", title: "Href", type: "string" }),
  ],
});

export const homePage = defineType({
  name: "homePage",
  title: "Home Page",
  type: "document",
  fields: [
    defineField({ name: "heroEyebrow", title: "Hero Eyebrow", type: "string" }),
    defineField({ name: "heroTitle", title: "Hero Title", type: "string" }),
    defineField({ name: "heroDescription", title: "Hero Description", type: "text", rows: 4 }),
    defineField({ name: "heroPracticalNote", title: "Hero Practical Note", type: "string" }),
    defineField({ name: "heroImageUrl", title: "Hero Image URL", type: "url" }),
    defineField({ name: "heroVideoUrl", title: "Hero Video URL", type: "url" }),
    defineField({ name: "heroPrimaryCtaLabel", title: "Hero Primary CTA Label", type: "string" }),
    defineField({ name: "heroPrimaryCtaHref", title: "Hero Primary CTA Href", type: "string" }),
    defineField({ name: "heroSecondaryCtaLabel", title: "Hero Secondary CTA Label", type: "string" }),
    defineField({ name: "heroSecondaryCtaHref", title: "Hero Secondary CTA Href", type: "string" }),
    defineField({ name: "heroStats", title: "Hero Pills", type: "array", of: [{ type: "string" }] }),
    defineField({
      name: "heroLinks",
      title: "Hero Bottom Links",
      type: "array",
      of: [{ type: "object", fields: linkField.fields }],
    }),

    defineField({ name: "whyChooseEyebrow", title: "Why Choose Eyebrow", type: "string" }),
    defineField({ name: "whyChooseTitle", title: "Why Choose Title", type: "string" }),
    defineField({ name: "whyChooseDescription", title: "Why Choose Description", type: "text", rows: 3 }),
    defineField({ name: "whyChooseSecondaryText", title: "Why Choose Secondary Text", type: "text", rows: 3 }),
    defineField({ name: "whyChooseImageUrl", title: "Why Choose Image URL", type: "url" }),
    defineField({ name: "whyChooseMediaTitle", title: "Why Choose Media Title", type: "string" }),
    defineField({ name: "whyChooseMediaDescription", title: "Why Choose Media Description", type: "text", rows: 3 }),
    defineField({ name: "whyChoosePills", title: "Why Choose Pills", type: "array", of: [{ type: "string" }] }),
    defineField({
      name: "whyChooseCards",
      title: "Why Choose Cards",
      type: "array",
      of: [
        {
          type: "object",
          fields: [
            defineField({ name: "title", title: "Title", type: "string" }),
            defineField({ name: "description", title: "Description", type: "text", rows: 3 }),
          ],
        },
      ],
    }),

    defineField({ name: "founderEyebrow", title: "Founder Eyebrow", type: "string" }),
    defineField({ name: "founderTitle", title: "Founder Section Title", type: "string" }),
    defineField({ name: "founderRole", title: "Founder Role", type: "string" }),
    defineField({ name: "founderQuote", title: "Founder Quote", type: "text", rows: 3 }),
    defineField({
      name: "founderPortrait",
      title: "Founder Portrait",
      type: "image",
      options: { hotspot: true },
    }),
    defineField({ name: "founderPortraitKicker", title: "Founder Portrait Kicker", type: "string" }),
    defineField({ name: "founderPortraitBadgeText", title: "Founder Portrait Badge Text", type: "text", rows: 3 }),
    defineField({ name: "founderHighlights", title: "Founder Highlights", type: "array", of: [{ type: "string" }] }),
    defineField({ name: "founderStory", title: "Founder Story", type: "array", of: [{ type: "block" }] }),
    defineField({ name: "founderPrimaryCtaLabel", title: "Founder Primary CTA Label", type: "string" }),
    defineField({ name: "founderPrimaryCtaHref", title: "Founder Primary CTA Href", type: "string" }),
    defineField({ name: "founderSecondaryCtaLabel", title: "Founder Secondary CTA Label", type: "string" }),
    defineField({ name: "founderSecondaryCtaHref", title: "Founder Secondary CTA Href", type: "string" }),

    defineField({ name: "servicesEyebrow", title: "Services Eyebrow", type: "string" }),
    defineField({ name: "servicesTitle", title: "Services Title", type: "string" }),
    defineField({ name: "servicesDescription", title: "Services Description", type: "text", rows: 3 }),
    defineField({ name: "servicesImageUrl", title: "Services Image URL", type: "url" }),
    defineField({ name: "servicesVideoUrl", title: "Services Video URL", type: "url" }),
    defineField({ name: "servicesMediaKicker", title: "Services Media Kicker", type: "string" }),
    defineField({ name: "servicesMediaCaption", title: "Services Media Caption", type: "text", rows: 3 }),
    defineField({ name: "servicesMediaButtonLabel", title: "Services Media Button Label", type: "string" }),
    defineField({ name: "servicesMediaButtonHref", title: "Services Media Button Href", type: "string" }),
    defineField({ name: "servicesPoints", title: "Services Points", type: "array", of: [{ type: "string" }] }),
    defineField({
      name: "serviceCards",
      title: "Service Cards",
      type: "array",
      of: [
        {
          type: "object",
          fields: [
            defineField({ name: "title", title: "Title", type: "string" }),
            defineField({ name: "summary", title: "Summary", type: "text", rows: 3 }),
          ],
        },
      ],
    }),

    defineField({ name: "healthPlanEyebrow", title: "Health Plan Eyebrow", type: "string" }),
    defineField({ name: "healthPlanTitle", title: "Health Plan Title", type: "string" }),
    defineField({ name: "healthPlanDescription", title: "Health Plan Description", type: "text", rows: 3 }),
    defineField({ name: "healthPlanSecondaryText", title: "Health Plan Secondary Text", type: "text", rows: 3 }),
    defineField({ name: "healthPlanPrimaryCtaLabel", title: "Health Plan Primary CTA Label", type: "string" }),
    defineField({ name: "healthPlanPrimaryCtaHref", title: "Health Plan Primary CTA Href", type: "string" }),
    defineField({ name: "healthPlanSecondaryCtaLabel", title: "Health Plan Secondary CTA Label", type: "string" }),
    defineField({ name: "healthPlanSecondaryCtaHref", title: "Health Plan Secondary CTA Href", type: "string" }),
    defineField({ name: "healthPlanVideoUrl", title: "Health Plan Video URL", type: "url" }),
    defineField({ name: "healthPlanPosterUrl", title: "Health Plan Poster URL", type: "url" }),
    defineField({ name: "healthPlanCardEyebrow", title: "Health Plan Card Eyebrow", type: "string" }),
    defineField({ name: "healthPlanCardTitle", title: "Health Plan Card Title", type: "string" }),
    defineField({
      name: "healthPlanTiers",
      title: "Health Plan Tiers",
      type: "array",
      of: [
        {
          type: "object",
          fields: [
            defineField({ name: "title", title: "Title", type: "string" }),
            defineField({ name: "detail", title: "Detail", type: "text", rows: 3 }),
            defineField({ name: "pricing", title: "Pricing", type: "string" }),
          ],
        },
      ],
    }),
    defineField({ name: "healthPlanBenefits", title: "Health Plan Benefits", type: "array", of: [{ type: "string" }] }),

    defineField({ name: "trustEyebrow", title: "Trust Eyebrow", type: "string" }),
    defineField({ name: "trustTitle", title: "Trust Title", type: "string" }),
    defineField({ name: "trustText", title: "Trust Text", type: "text", rows: 3 }),
    defineField({ name: "trustImageUrl", title: "Trust Image URL", type: "url" }),
    defineField({ name: "trustPills", title: "Trust Pills", type: "array", of: [{ type: "string" }] }),
    defineField({ name: "trustHighlights", title: "Trust Highlights", type: "array", of: [{ type: "string" }] }),
    defineField({
      name: "trustModules",
      title: "Trust Modules",
      type: "array",
      of: [
        {
          type: "object",
          fields: [
            defineField({ name: "tag", title: "Tag", type: "string" }),
            defineField({ name: "title", title: "Title", type: "string" }),
            defineField({ name: "text", title: "Text", type: "text", rows: 3 }),
          ],
        },
      ],
    }),
    defineField({ name: "locationEyebrow", title: "Location Eyebrow", type: "string" }),
    defineField({ name: "locationTitle", title: "Location Title", type: "string" }),
    defineField({ name: "locationAddress", title: "Location Address", type: "string" }),
    defineField({ name: "locationDirectionsLabel", title: "Location Directions Label", type: "string" }),
    defineField({ name: "locationDirectionsHref", title: "Location Directions Href", type: "string" }),
    defineField({ name: "locationPoints", title: "Location Points", type: "array", of: [{ type: "string" }] }),
    defineField({ name: "locationMapImageUrl", title: "Location Map Image URL", type: "url" }),
    defineField({ name: "homepageVideoUrl", title: "Homepage Video URL", type: "url" }),
    defineField({ name: "homepageVideoEyebrow", title: "Homepage Video Eyebrow", type: "string" }),
    defineField({ name: "homepageVideoTitle", title: "Homepage Video Title", type: "string" }),
    defineField({ name: "homepageVideoDescription", title: "Homepage Video Description", type: "text", rows: 3 }),
    defineField({ name: "homepageVideoActionLabel", title: "Homepage Video Action Label", type: "string" }),

    defineField({ name: "adviceEyebrow", title: "Advice Eyebrow", type: "string" }),
    defineField({ name: "adviceTitle", title: "Advice Title", type: "string" }),
    defineField({ name: "adviceIntroText", title: "Advice Intro Text", type: "text", rows: 3 }),
    defineField({ name: "adviceCtaLabel", title: "Advice CTA Label", type: "string" }),
    defineField({ name: "adviceCtaHref", title: "Advice CTA Href", type: "string" }),
    defineField({ name: "advicePills", title: "Advice Pills", type: "array", of: [{ type: "string" }] }),
    defineField({ name: "adviceFeaturedImageUrl", title: "Advice Featured Image URL", type: "url" }),
    defineField({ name: "adviceSecondaryImageUrl", title: "Advice Secondary Image URL", type: "url" }),
    defineField({
      name: "adviceArticles",
      title: "Advice Articles",
      type: "array",
      of: [
        {
          type: "object",
          fields: [
            defineField({ name: "category", title: "Category", type: "string" }),
            defineField({ name: "date", title: "Date", type: "string" }),
            defineField({ name: "title", title: "Title", type: "string" }),
            defineField({ name: "excerpt", title: "Excerpt", type: "text", rows: 3 }),
            defineField({ name: "meta", title: "Meta", type: "string" }),
            defineField({ name: "cta", title: "CTA", type: "string" }),
            defineField({ name: "href", title: "Href", type: "string" }),
          ],
        },
      ],
    }),
    defineField({ name: "socialEyebrow", title: "Social Eyebrow", type: "string" }),
    defineField({ name: "socialTitle", title: "Social Title", type: "string" }),
    defineField({ name: "socialDescription", title: "Social Description", type: "text", rows: 3 }),
    defineField({ name: "socialInstagramLabel", title: "Instagram Button Label", type: "string" }),
    defineField({ name: "socialTikTokLabel", title: "TikTok Button Label", type: "string" }),
    defineField({
      name: "socialCards",
      title: "Social Cards",
      type: "array",
      of: [
        {
          type: "object",
          fields: [
            defineField({ name: "platform", title: "Platform", type: "string" }),
            defineField({ name: "title", title: "Title", type: "string" }),
            defineField({ name: "caption", title: "Caption", type: "text", rows: 3 }),
            defineField({ name: "image", title: "Image URL", type: "url" }),
          ],
        },
      ],
    }),

    defineField({ name: "ctaEyebrow", title: "CTA Eyebrow", type: "string" }),
    defineField({ name: "ctaTitle", title: "CTA Title", type: "string" }),
    defineField({ name: "ctaText", title: "CTA Text", type: "text", rows: 3 }),
    defineField({ name: "ctaPrimaryLabel", title: "CTA Primary Label", type: "string" }),
    defineField({ name: "ctaPrimaryHref", title: "CTA Primary Href", type: "string" }),
    defineField({ name: "ctaSecondaryLabel", title: "CTA Secondary Label", type: "string" }),
    defineField({ name: "ctaSecondaryHref", title: "CTA Secondary Href", type: "string" }),
  ],
});
