import { healthPlanPageSeed } from "@/lib/healthPlanSeed";
import { feeCategorySeeds, pricingPageSeed } from "@/lib/pricingSeed";
import {
  accessibilitySections,
  blogPreview,
  cookieInventory,
  cookieSections,
  founderStory,
  healthPlanTiers,
  faqPreview,
  homeHighlights,
  homeHeroStats,
  homeMedia,
  legalPageCopy,
  locationPoints,
  practiceTourPreview,
  privacySections,
  serviceDetails,
  siteConfig,
  socialPreviewCards,
  termsSections,
  trustHighlights,
  trustIntro,
  trustModules,
} from "@/lib/site";
import { fallbackTeamMembers, teamPageSeed } from "@/lib/teamSeed";
import { masterServiceGroups, seededServices, servicesPageSeed } from "@/lib/servicesSeed";
import { visualAssets } from "@/lib/visualAssets";
import { careersPageDefaults, defaultVacancy } from "@/lib/careersContent";

type SanitySeedDocument = Record<string, unknown>;

const homePageSeedDocument: SanitySeedDocument = {
  _id: "homePage",
  _type: "homePage",
  heroEyebrow: "Independent veterinary care in Sutton",
  heroTitle: "Calm, independent vet care in Sutton.",
  heroDescription:
    "Kind, practical care with a calm personal approach.",
  heroPracticalNote: "Near Hackbridge station, with practical parking guidance surfaced early for first visits.",
  heroImageUrl: visualAssets.homeHeroClient,
  heroVideoUrl: "https://videos.pexels.com/video-files/6230151/6230151-hd_1920_1080_25fps.mp4",
  heroPrimaryCtaLabel: "Register Now",
  heroPrimaryCtaHref: siteConfig.ctas.register,
  heroSecondaryCtaLabel: "Book Online",
  heroSecondaryCtaHref: siteConfig.ctas.book,
  heroStats: homeHeroStats,
  heroLinks: [
    { label: "Services", href: "/services" },
    { label: "Health Plan", href: "/health-plan" },
    { label: "Contact", href: "/contact" },
  ],
  introEyebrow: "Independent Care",
  introTitle: "Calm care, clear services, and practical next steps.",
  introParagraphs: [
    "The Sutton Vet is an independent practice built around calm guidance, modern clinical standards, and clear information.",
    "From appointments to surgery, diagnostics, endoscopy, and daytime urgent care, services are listed clearly.",
  ],
  introNoteLabel: "Services available",
  introNoteText: "Soft tissue surgery, orthopaedic surgery, and endoscopy are included.",
  whyChooseEyebrow: "Why Choose The Sutton Vet",
  whyChooseTitle: "Independent, transparent, and reassuring from day one.",
  whyChooseDescription:
    "Local ownership, practical pricing clarity, and compassionate evidence-based care should all feel clear within seconds.",
  whyChooseSecondaryText:
    "The aim is to make new clients in Sutton feel informed, calmer, and more confident before they even get in touch.",
  whyChooseImageUrl: homeMedia.whyChooseImage,
  whyChooseMediaTitle: "Modern facilities",
  whyChooseMediaDescription: "Calmer, clearer clinical surroundings help first visits feel less overwhelming.",
  whyChoosePills: ["Local ownership", "Clear pricing cues", "Modern facilities"],
  whyChooseCards: homeHighlights.map((item) => ({
    title: item.title,
    description: item.description,
  })),
  founderEyebrow: founderStory.eyebrow,
  founderTitle: founderStory.title,
  founderRole: founderStory.role,
  founderQuote: founderStory.quote,
  founderPortraitKicker: "Founder portrait",
  founderPortraitBadgeText: "Professional founder photography can be replaced from the CMS later.",
  founderHighlights: founderStory.highlights,
  founderStory: founderStory.paragraphs.map((text) => ({
    _type: "block",
    children: [{ _type: "span", text }],
  })),
  founderPrimaryCtaLabel: "Register Now",
  founderPrimaryCtaHref: siteConfig.ctas.register,
  founderSecondaryCtaLabel: "Talk to our team on WhatsApp",
  founderSecondaryCtaHref: siteConfig.ctas.whatsapp,
  servicesEyebrow: "Care Overview",
  servicesTitle: "Care, diagnostics, procedures, home visits, and daytime urgent support.",
  servicesDescription:
    "A simple overview of the care available at The Sutton Vet.",
  servicesImageUrl: homeMedia.servicesImage,
  servicesVideoUrl: homeMedia.servicesVideo,
  servicesMediaKicker: "Services overview",
  servicesMediaCaption: "Use the services page for fuller clinical detail while the homepage stays clean and directional.",
  servicesMediaButtonLabel: "View Services",
  servicesMediaButtonHref: "/services",
  servicesPoints: serviceDetails.map((item) => item.title),
  healthPlanEyebrow: "Health plan",
  healthPlanTitle: "Spread routine care costs without making the page feel sales-led.",
  healthPlanDescription:
    "The homepage teaser should explain the plan simply, then let owners choose whether to go deeper into the dedicated Health Plan journey.",
  healthPlanSecondaryText:
    "This section builds trust before asking for a deeper commitment, while still giving visitors a direct route into the dedicated Health Plan page and later the approved PMS / online portal workflow.",
  healthPlanPrimaryCtaLabel: "Explore Health Plan",
  healthPlanPrimaryCtaHref: "/health-plan",
  healthPlanSecondaryCtaLabel: "Read Common Questions",
  healthPlanSecondaryCtaHref: "/contact",
  healthPlanVideoUrl: "https://videos.pexels.com/video-files/854132/854132-hd_1920_1080_25fps.mp4",
  healthPlanPosterUrl: "https://images.unsplash.com/photo-1517849845537-4d257902454a?auto=format&fit=crop&w=1400&q=80",
  healthPlanCardEyebrow: "Plan snapshot",
  healthPlanCardTitle: "Built for dogs and cats with clear pricing logic.",
  healthPlanTiers: healthPlanTiers.map((item) => ({
    title: item.title,
    detail: item.detail,
    pricing: item.pricing,
  })),
  healthPlanBenefits: ["Different from insurance", "Predictable monthly budgeting", "Clear route to sign-up later"],
  trustEyebrow: trustIntro.eyebrow,
  trustTitle: trustIntro.title,
  trustText: trustIntro.text,
  trustImageUrl: homeMedia.trustImage,
  trustPills: ["Founder-led", "Registrations open", "CMS swappable content"],
  trustHighlights,
  trustModules: trustModules.map((item) => ({
    tag: item.tag,
    title: item.title,
    text: item.text,
  })),
  locationEyebrow: "Find us",
  locationTitle: "Exact location and directions should be clear early.",
  locationAddress: siteConfig.address,
  locationDirectionsLabel: "Get directions",
  locationDirectionsHref: "https://maps.google.com/?q=4%20Spinning%20Wheel%20Way%2C%20Sutton%2C%20SM6%207DS",
  locationPoints,
  locationMapImageUrl: homeMedia.trustImage,
  homepageVideoUrl: "",
  homepageVideoEyebrow: "Practice Tour",
  homepageVideoTitle: practiceTourPreview.title,
  homepageVideoDescription: practiceTourPreview.text,
  homepageVideoActionLabel: "Open on YouTube",
  adviceEyebrow: "Advice & Content",
  adviceTitle: "Latest advice",
  adviceIntroText: "Two clear recent articles are enough on the homepage. The fuller editorial browse belongs on the blog page.",
  adviceCtaLabel: "View blog",
  adviceCtaHref: "/contact",
  advicePills: ["Latest articles", "Practical pet advice", "Read more flow"],
  adviceFeaturedImageUrl: homeMedia.adviceFeaturedImage,
  adviceSecondaryImageUrl: homeMedia.adviceSecondaryImage,
  adviceArticles: blogPreview.map((item) => ({
    category: item.category,
    date: item.date,
    title: item.title,
    excerpt: item.excerpt,
    meta: item.meta,
    cta: item.cta,
    href: "/contact",
  })),
  socialEyebrow: "Social preview",
  socialTitle: "Social updates",
  socialDescription: "A lighter visual strip for Instagram and TikTok style content, with each card linking outward rather than loading heavy embeds into the homepage.",
  socialInstagramLabel: "Open Instagram",
  socialTikTokLabel: "Open TikTok",
  socialCards: socialPreviewCards.map((item) => ({
    platform: item.platform,
    title: item.title,
    caption: item.caption,
    image: item.image,
  })),
  ctaEyebrow: "Next Step",
  ctaTitle: "Ready to register or ask a question?",
  ctaText: "Every page should still end with a clear route into booking, registration, or direct contact.",
  ctaPrimaryLabel: "Register Now",
  ctaPrimaryHref: siteConfig.ctas.register,
  ctaSecondaryLabel: "Book Online",
  ctaSecondaryHref: siteConfig.ctas.book,
};

const siteSettingsSeedDocument: SanitySeedDocument = {
  _id: "siteSettings",
  _type: "siteSettings",
  practiceName: siteConfig.name,
  shortName: siteConfig.shortName,
  tagline: siteConfig.tagline,
  footerTagline: "Independent veterinary care in Sutton.",
  topbarNote: siteConfig.topbarNote,
  phone: siteConfig.phone,
  emergencyPhone: siteConfig.emergencyPhone,
  email: siteConfig.email,
  address: siteConfig.address,
  openingHours: [
    { day: "Monday", hours: "09:00am - 6:00pm" },
    { day: "Tuesday", hours: "09:00am - 6:00pm" },
    { day: "Wednesday", hours: "09:00am - 6:00pm" },
    { day: "Thursday", hours: "09:00am - 6:00pm" },
    { day: "Friday", hours: "09:00am - 6:00pm" },
    { day: "Saturday", hours: "9:00am - 12.00pm" },
    { day: "Sunday", hours: "Closed" },
  ],
  whatsappNumber: "923063892101",
  whatsappPrefillMessage: "Hi The Sutton Vet, I have a question about registering my pet.",
  lupaBookingUrl: siteConfig.ctas.book,
  lupaRegistrationUrl: siteConfig.ctas.register,
  healthPlanUrl: siteConfig.ctas.healthPlan,
  googleBusinessProfileUrl: siteConfig.googleProfile,
  googleMapEmbedUrl: "https://www.google.com/maps?q=4%20Spinning%20Wheel%20Way%2C%20Sutton%2C%20SM6%207DS&output=embed",
  hasMapUrl: "https://maps.google.com/?q=4%20Spinning%20Wheel%20Way%2C%20Sutton%2C%20SM6%207DS",
  knowsAbout: [
    "Independent veterinary care",
    "Consultations",
    "Diagnostics",
    "X-ray",
    "Ultrasound",
    "Surgery",
    "Dentistry",
    "Preventative care",
    "Health plans",
    "Sutton",
    "Hackbridge",
    "Beddington Park",
  ],
  socialLinks: siteConfig.socials.map((item) => ({
    label: item.label,
    href: item.href,
    icon: item.label,
  })),
  mainNav: siteConfig.mainNav,
  legalLinks: siteConfig.legalLinks,
  headerCtas: {
    emergencyLabel: "Emergency",
    bookLabel: "Book Online",
    registerLabel: "Register Now",
  },
  complianceLines: [
    siteConfig.compliance.registeredCompany,
    siteConfig.compliance.tradingName,
    siteConfig.compliance.vatNumber,
    "Registered office address: to be confirmed and inserted in full before go-live.",
    siteConfig.compliance.practiceAddress,
    "Premises Registration Number (RCVS/VMD): to be confirmed and inserted once issued.",
  ],
  chatSettings: {
    eyebrow: "Chat Help",
    title: "How can we help?",
    introLabel: "Practice information",
    introText: "Ask about services, opening hours, location, pricing, Health Plans, careers, registration, or booking. For urgent concerns, please call the practice.",
    topicButtons: [
      { label: "Services", query: "What services do you offer?" },
      { label: "Opening hours", query: "What are your opening hours?" },
      { label: "Parking & location", query: "Where are you located and is parking available?" },
      { label: "Pricing", query: "How does pricing work?" },
      { label: "Health Plan", query: "Can you explain the Health Plan?" },
      { label: "Careers", query: "Are you currently hiring?" },
      { label: "Register & book", query: "How do I register or book?" },
    ],
    inputPlaceholder: "Services, hours, pricing, careers, booking...",
    hoursReply: "The practice is open Monday to Friday, 9:00am to 6:00pm, and Saturday, 9:00am to 12:00pm. Sunday is closed. Please call for urgent guidance.",
    locationReply: "The Sutton Vet is at 4 Spinning Wheel Way, Hackbridge, Sutton, SM6 7DS. Nearby parking and step-free access information is available on the Contact page.",
    feesReply: "Services are listed on the website. Where a final price depends on assessment, patient size, or the procedure, the team will provide a quote before treatment.",
    planReply: "The Health Plan is currently presented as information only while the final provider and sign-up process are confirmed. Plan details can be updated on the website as soon as they are available.",
    bookingReply: "Online registration and booking are being connected through Lupa. If the online journey is unavailable, please call or message the practice and the team will help directly.",
    servicesReply: "The practice offers consultations, daytime urgent care, preventative care, vaccinations, dentistry, diagnostics, surgery, orthopaedic procedures, endoscopy, home visits, and sensitive end-of-life support. Open the Services menu for full details.",
    careersReply: "The Sutton Vet is currently advertising a Veterinary Nurse opportunity. Visit the Careers page for the role overview and application email.",
    contactReply: "Call 0203 603 0298 or email info@thesuttonvet.co.uk. You can also use the Contact page for directions, parking, and opening times.",
    paymentsReply: "There is no Lupa Pay integration planned. Please contact the practice for current payment arrangements and any available options.",
    fallbackReply: "I can help with practice information only. Ask about services, hours, location, pricing, Health Plans, careers, registration, or booking. For clinical advice or urgent concerns, please call the practice.",
    emergencyLabel: "Urgent help",
    emergencyReply: "This chat cannot provide clinical advice. If you are worried your pet may need urgent care, please call the practice now.",
    emergencyButtonLabel: "Call the practice",
    registerButtonLabel: "Register Online",
    whatsappButtonLabel: "Message the team",
  },
};

const emergencySettingsSeedDocument: SanitySeedDocument = {
  _id: "emergencySettings",
  _type: "emergencySettings",
  inHoursMessage: "During opening hours, call the main practice number first for urgent concerns.",
  outOfHoursMessage: "Outside practice hours, use the emergency line immediately for urgent issues.",
  emergencyPhone: siteConfig.emergencyPhone,
  keywords: [
    "bleeding",
    "blood",
    "poison",
    "poisoned",
    "breathing",
    "collapsed",
    "collapse",
    "seizure",
    "seizing",
    "fit",
    "fits",
    "unresponsive",
    "not breathing",
    "hit by car",
    "accident",
    "emergency",
    "urgent",
  ],
};

const contactPageSeedDocument: SanitySeedDocument = {
  _id: "contactPage",
  _type: "contactPage",
  heroEyebrow: "Contact & Emergency Care",
  heroTitle: "Simple contact, clear urgent routing.",
  heroDescription: "For bookings, registration, location guidance, and out-of-hours support, this page should make the next step obvious within seconds.",
  heroImageUrl: "https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?auto=format&fit=crop&w=1800&q=80",
  heroPrimaryCtaLabel: "Book Online",
  heroPrimaryCtaHref: siteConfig.ctas.book,
  heroSecondaryCtaLabel: "Register Now",
  heroSecondaryCtaHref: siteConfig.ctas.register,
  summaryEyebrow: "At A Glance",
  quickLinks: [
    { title: "Call us", value: siteConfig.phone, href: siteConfig.ctas.call, meta: "Fastest route for appointments and practical questions", icon: "phone" },
    { title: "Visit us", value: siteConfig.address, href: "https://maps.google.com/?q=4%20Spinning%20Wheel%20Way%2C%20Sutton%2C%20SM6%207DS", meta: "Directions, local travel guidance, and nearby access", icon: "pin" },
    { title: "Email us", value: siteConfig.email, href: `mailto:${siteConfig.email}`, meta: "Useful for non-urgent admin and document requests", icon: "mail" },
    { title: "Connect with us", value: "Instagram & Facebook", href: siteConfig.socials[1]?.href || "/", meta: "Follow updates and opening momentum as the practice grows", icon: "share" },
  ],
  openEyebrow: "Open Practice Hours",
  openTitle: "Book, register, or ask a practical question.",
  openDescription: "During practice hours, the quickest route is to call, book online, or use the registration flow.",
  parkingEyebrow: "Parking & Access",
  parkingTitle: "Arrival guidance for a calmer first visit.",
  openMetaLines: [`Phone: ${siteConfig.phone}`, `Address: ${siteConfig.address}`, `Email: ${siteConfig.email}`],
  openCtas: [
    { label: "Book Online", href: siteConfig.ctas.book, variant: "primary" },
    { label: "Register Now", href: siteConfig.ctas.register, variant: "muted" },
  ],
  emergencyEyebrow: "Out-of-Hours Emergency Care",
  emergencyTitle: "Urgent care should feel immediate and unmistakable.",
  emergencyDescription: "If the practice is closed and your pet needs urgent help, call the emergency line straight away.",
  emergencyPoints: [
    "Use the emergency number outside normal practice hours",
    "In-hours urgent cases should still call the main practice number first",
    "Emergency routing remains prominent on mobile and sticky navigation paths",
  ],
  emergencyButtonLabel: "Call Emergency Line",
  hoursEyebrow: "Opening Hours",
  hoursTitle: "When we are open",
  communityEyebrow: "Community",
  communityTitle: "Passionate about animals and our community.",
  communityText: "A local practice supporting pet education, animal welfare, and neighbourhood connection.",
  detailsEyebrow: "Contact Details",
  detailsTitle: "Everything important, in one place.",
  locationEyebrow: "Find Us",
  locationTitle: "How to find us",
  locationDescription: `The Sutton Vet is based at ${siteConfig.address}. The contact journey should reassure new clients with a clear map, straightforward access guidance, and practical next steps before the visit.`,
  locationPoints: [
    "Hackbridge and Sutton coverage surfaced clearly for local reassurance",
    "Directions and map access available without extra clicks",
    "Call first if you need help with parking or arrival guidance",
  ],
  locationButtonLabel: "Get Directions",
  locationButtonHref: "https://maps.google.com/?q=4%20Spinning%20Wheel%20Way%2C%20Sutton%2C%20SM6%207DS",
  locationMapEmbedUrl: "https://www.google.com/maps?q=4%20Spinning%20Wheel%20Way%2C%20Sutton%2C%20SM6%207DS&output=embed",
  locationMapLabelTitle: "The Sutton Vet",
  locationMapLabelText: siteConfig.address,
  socialCards: [
    { title: "Facebook", description: "Updates, launch momentum, and local practice news.", ctaLabel: "Join us", href: siteConfig.socials[0]?.href || "/", icon: "facebook" },
    { title: "Instagram", description: "Follow practice visuals, opening updates, and behind-the-scenes content.", ctaLabel: "Follow us", href: siteConfig.socials[1]?.href || "/", icon: "instagram" },
  ],
  ctaEyebrow: "Next Step",
  ctaTitle: "Need help before booking?",
  ctaText: "Call, WhatsApp, or use the online booking route if you want help choosing the right next step.",
  ctaPrimaryLabel: "WhatsApp Our Team",
  ctaPrimaryHref: siteConfig.ctas.whatsapp,
  ctaSecondaryLabel: "Book Online",
  ctaSecondaryHref: siteConfig.ctas.book,
};

const faqPageSeedDocument: SanitySeedDocument = {
  _id: "faqPage",
  _type: "faqPage",
  eyebrow: "FAQ",
  title: "Common practical questions, answered clearly.",
  description: "Clear answers around fees, first visits, parking, emergencies, and registration.",
  ctaTitle: "Still need help?",
  ctaText: "Contact, book, or call from here.",
  ctaPrimaryLabel: "Book Online",
  ctaPrimaryHref: siteConfig.ctas.book,
  ctaSecondaryLabel: "Register Now",
  ctaSecondaryHref: siteConfig.ctas.register,
};

const faqSeedDocuments: SanitySeedDocument[] = faqPreview.map((item, index) => ({
  _id: `faq-${index + 1}`,
  _type: "faq",
  question: item.question,
  answer: item.answer,
  category:
    index === 0
      ? "Registration"
      : index === 1
        ? "First Visit"
        : index === 2
          ? "Health Plan"
          : "Emergency",
  displayOrder: index + 1,
}));

const firstVisitPageSeedDocument: SanitySeedDocument = {
  _id: "firstVisitPage",
  _type: "firstVisitPage",
  eyebrow: "New Client / First Visit Guide",
  title: "A calmer first visit starts with clearer preparation.",
  description: "Simple guidance for registration, what to bring, and what to expect during the first consultation.",
  steps: [
    "Register through the online portal flow before the appointment where possible.",
    "Bring previous records, medication details, and any insurance information.",
    "Expect a calm first consultation with practical next-step guidance.",
  ],
  ctaTitle: "Ready to register first?",
  ctaText: "A simple route into the online portal starts here.",
  ctaPrimaryLabel: "Register Now",
  ctaPrimaryHref: siteConfig.ctas.register,
  ctaSecondaryLabel: "Book Online",
  ctaSecondaryHref: siteConfig.ctas.book,
};

const teamPageSeedDocument: SanitySeedDocument = {
  _id: "teamPage",
  _type: "teamPage",
  ...teamPageSeed,
  promiseEyebrow: "Team Promise",
  promiseTitle: "Care should feel clear before, during, and after the appointment.",
  values: ["Kind communication", "Clear clinical options", "A calmer visit", "Continuity of care"],
  ctaTitle: "Meet us in person?",
  ctaText: "Register, contact, or book online when you're ready.",
  ctaPrimaryLabel: "Book Online",
  ctaPrimaryHref: siteConfig.ctas.book,
  ctaSecondaryLabel: "Register Now",
  ctaSecondaryHref: siteConfig.ctas.register,
};

const teamMemberSeedDocuments: SanitySeedDocument[] = fallbackTeamMembers.map((member) => ({
  _id: member.id,
  _type: "teamMember",
  name: member.name,
  role: member.role,
  category: member.category,
  qualifications: member.qualifications,
  shortBio: member.shortBio,
  bio: member.bio,
  imageUrl: member.imageUrl,
  displayOrder: member.displayOrder,
}));

const blogPageSeedDocument: SanitySeedDocument = {
  _id: "blogPage",
  _type: "blogPage",
  eyebrow: "Blog & Pet Advice",
  title: "Pet advice",
  description: "Clear, practical articles for new clients and routine pet care questions, presented in a calmer editorial layout.",
  introEyebrow: "Latest Advice",
  introTitle: "Latest reads",
  introDescription: "Short, practical reads should help owners find the next useful answer quickly, without turning the page into a crowded news feed.",
  feedbackEyebrow: "Article feedback",
  feedbackTitle: "Was this article useful?",
  feedbackDescription: "Quick feedback helps shape which advice should be clearer, shorter, or surfaced earlier across the site.",
  feedbackHelperLabel: "Contact the practice",
  feedbackHelperHref: "/contact",
  feedbackHelpfulLabel: "Helpful",
  feedbackMoreLabel: "Need more detail",
  feedbackContactLabel: "I need to speak to someone",
  feedbackHelpfulResponse: "Thanks. This signals that the article answered the question clearly.",
  feedbackMoreResponse: "Thanks. This helps highlight where future advice needs more practical detail.",
  feedbackContactResponse: "Thanks. If the issue feels urgent or specific to your pet, direct contact is the safer next step.",
  browseMoreLabel: "Browse more advice",
  browseMoreHref: "/contact",
  askDirectLabel: "Ask the team directly",
  askDirectHref: "/contact",
  ctaTitle: "Need guidance sooner?",
  ctaText: "If the question feels urgent, contact the practice directly rather than waiting to read further.",
  ctaPrimaryLabel: "Contact Us",
  ctaPrimaryHref: "/contact",
  ctaSecondaryLabel: "Book Online",
  ctaSecondaryHref: siteConfig.ctas.book,
};

const legalPageSeedDocuments: SanitySeedDocument[] = [
  {
    _id: "legal-privacy-policy",
    _type: "legalPage",
    title: "Privacy policy",
    eyebrow: "Privacy Policy",
    pageType: "Privacy Policy",
    description: legalPageCopy.privacy,
    sections: privacySections,
  },
  {
    _id: "legal-cookie-policy",
    _type: "legalPage",
    title: "Cookie policy",
    eyebrow: "Cookie Policy",
    pageType: "Cookie Policy",
    description: legalPageCopy.cookies,
    sections: [
      {
        title: "Consent principles",
        status: "Mandatory",
        body: [
          "Optional analytics and external-media technologies must remain blocked until the visitor actively opts in.",
          "Accept and Reject should remain equally prominent, with no pre-ticked boxes and no background loading of optional scripts before consent.",
          "On this site, optional categories default to off and third-party embeds should remain blocked until the visitor opts in.",
        ],
      },
      ...cookieSections.map((section) => ({
        title: section.title,
        status: section.status,
        body: [section.body],
      })),
    ],
    inventoryItems: cookieInventory,
  },
  {
    _id: "legal-accessibility",
    _type: "legalPage",
    title: "Accessibility",
    eyebrow: "Accessibility Statement",
    pageType: "Accessibility Statement",
    description: legalPageCopy.accessibility,
    sections: accessibilitySections,
  },
  {
    _id: "legal-terms",
    _type: "legalPage",
    title: "Terms of business",
    eyebrow: "Terms of Business",
    pageType: "Terms of Business",
    description: legalPageCopy.terms,
    sections: termsSections,
  },
];

export const servicesPageSeedDocument: SanitySeedDocument = {
  ...servicesPageSeed,
};

export const serviceSeedDocuments: SanitySeedDocument[] = seededServices.map((service) => ({
  ...service,
}));

const serviceCategoryTargets: Record<string, string> = {
  "Pet Club and preventative care": "service-pet-club-preventative-care",
  "Vaccinations and routine procedures": "service-vaccinations",
  "Dentistry, imaging, and diagnostics": "service-in-house-diagnostics",
  "Soft tissue procedures": "service-service-soft-tissue",
  "Orthopaedic procedures": "service-service-orthopaedic",
  "Endoscopy and sensitive care": "service-service-endoscopy",
};

export const serviceCategorySeedDocuments: SanitySeedDocument[] = masterServiceGroups.map((group, index) => ({
  _id: `service-category-${index + 1}`,
  _type: "serviceCategory",
  title: group.title,
  description: group.description,
  highlights: group.items,
  sortOrder: index + 1,
  active: true,
  featuredService: { _type: "reference", _ref: serviceCategoryTargets[group.title] },
}));

export const healthPlanPageSeedDocument: SanitySeedDocument = {
  _id: "healthPlanPage",
  _type: "healthPlan",
  ...healthPlanPageSeed,
};

export const pricingPageSeedDocument: SanitySeedDocument = {
  ...pricingPageSeed,
};

export const feeCategorySeedDocuments: SanitySeedDocument[] = feeCategorySeeds.map((category) => ({
  ...category,
}));

export const staleCmsDocumentTypes = ["blogPage", "blogPost", "faqPage", "faq", "firstVisitPage"];

export const staleCmsDocumentIds = [
  "blogPage",
  "firstVisitPage",
  "faqPage",
  "faq-1",
  "faq-2",
  "faq-3",
  "faq-4",
  "blog-first-visit-guide",
  "blog-preventative-care-plans",
  "blog-when-to-call-urgently",
  "blog-puppy-kitten-checks",
  "blog-early-diagnosis-matters",
  "blog-registering-before-visit",
  "blog-routine-health-checks",
  "blog-local-first-visit-planning",
  "service-referral-soft-tissue",
  "service-referral-orthopaedic",
  "service-referral-endoscopy",
];

export const allSeedDocuments: SanitySeedDocument[] = [
  {
    _id: "careersPage",
    _type: "careersPage",
    ...careersPageDefaults,
    vacanciesEyebrow: "Current opportunities",
    vacanciesTitle: "Find your place in our growing team.",
    heroCtaLabel: "View vacancies",
    heroBadgeEyebrow: "Now recruiting",
    heroBadgeTitle: "Veterinary professionals",
    hiringLabel: "Now hiring",
    applyTitle: "Interested?",
    applyText: "Send your CV and a short introduction.",
    roleDetailsLabel: "About this role",
    generalEnquiryText: "Interested in joining us? We'd love to hear from you.",
    generalEnquiryLabel: "Email the team",
  },
  {
    _id: "job-veterinary-nurse",
    _type: "jobVacancy",
    ...defaultVacancy,
  },
  siteSettingsSeedDocument,
  emergencySettingsSeedDocument,
  homePageSeedDocument,
  {
    _id: "aboutPage",
    _type: "aboutPage",
    heroEyebrow: "About The Sutton Vet",
    heroTitle: "Independent, family-owned, and rooted in Sutton.",
    heroDescription: "A small independent practice offering gentle, advanced veterinary care at fair prices.",
    heroImageUrl: visualAssets.aboutClinicCare,
    introEyebrow: "Our Approach",
    introTitle: "Care that feels warm, thoughtful, and clear.",
    introParagraphs: ["We offer a personalised, friendly, and caring service with objective options explained clearly.", "Our decisions are guided by kindness, clinical standards, and fairness."],
    storyEyebrow: "Our Story",
    storyTitle: "Born from values, not from a business model.",
    storyText: "The Sutton Vet was created to place animals, families, and ethical decision-making first.",
    carePillars: [
      { label: "Character", text: "Honesty, patience, and consistency when answers are not immediate." },
      { label: "Duty", text: "Continuity through every life stage." },
      { label: "Conscience", text: "Recommendations guided by what is right for each animal." },
    ],
    differenceEyebrow: "A Different Kind Of Veterinary Service",
    differenceTitle: "Small enough to know you, big enough to serve you.",
    differencePoints: ["Not rushed", "Fear-free handling", "See the same people", "Independent and locally vet-owned", "Transparent pricing", "Advanced care without compromise"],
    visitEyebrow: "Visit Information",
    visitTitle: "Opening times, parking, and access in one simple place.",
    visitDescription: "The clinic is based near Hackbridge Rail Station, with step-free access and nearby parking.",
    visitDetails: [
      { label: "Address", text: siteConfig.address },
      { label: "Access", text: "Ample parking and step-free access" },
      { label: "Monday - Friday", text: "09:00am - 6:00pm" },
      { label: "Saturday", text: "9:00am - 12.00pm" },
    ],
  },
  contactPageSeedDocument,
  teamPageSeedDocument,
  ...teamMemberSeedDocuments,
  ...legalPageSeedDocuments,
  servicesPageSeedDocument,
  ...serviceCategorySeedDocuments,
  ...serviceSeedDocuments,
  healthPlanPageSeedDocument,
  pricingPageSeedDocument,
  ...feeCategorySeedDocuments,
];

export function getSeedDocumentsByType(type: string) {
  return allSeedDocuments.filter((document) => document._type === type);
}





